### ISSUE TITLE
Table name is not supported as a parameter?

### ISSUE THREAD

**Issue by anentropic** [racket/db#20]
Docs show an example like:
```racket
(query-exec pgc "delete from the_numbers where n = $1" 42)
```

But trying to do this instead gives an error:
```racket
(query-exec db-conn
  "CREATE TABLE IF NOT EXISTS $1 (key text NOT NULL, value text NOT NULL, PRIMARY KEY (key))"
  "mytable")
```
```
; query-exec: near "$1": syntax error
;   error code: 1
; [,bt for context]
```

I guess this means that parameters are only allowed in certain query positions? I guess only for values, not for identifiers?

**Comment by rmculpepper** [comment]
That's right: SQL only allows placeholders in value positions. The docs at https://docs.racket-lang.org/db/using-db.html#(part._dbsec-sql-injection) mention that restriction:

> Only SQL literal values can be replaced with parameter placeholders; a SQL statement cannot be parameterized over a column name or a sort order, for example....

**Comment by anentropic** [comment]
Ah right, that is what I had ended up doing in the meantime anyway:
```racket
(format "SELECT key, value FROM ~a" table-name)
```

I was hoping to find a helper function that knows how to quote SQL identifiers so we can make this necessary bit of string formatting safer.

Your answer to [my other question on SO](https://stackoverflow.com/a/63220015/202168) shows how to do that now...

```racket
(require db sql)

(define (select-values db-conn table-name)
  (define db-type (dbsystem-name (connection-dbsystem db-conn)))
  (set! table-name
    (parameterize ((current-sql-dialect db-type))
      (sql-ast->string (ident-qq (Ident:AST ,(make-ident-ast table-name))))))
  (query-rows db-conn
    (format "SELECT key, value FROM ~a" table-name)))
```

Thanks for all your help 😄
